services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-backend-prod
    ports:
      - "8080:8080"
      - "8443:8443"
    # depends_on:
    #   - qdrant
    volumes:
      - ./certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetcore
      #- Qdrant__Url=http://qdrant:6333
      - Logging__LogLevel__Default=Debug

  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start -- --host 0.0.0.0"

  # qdrant:
  #   image: qdrant/qdrant:latest
  #   restart: always
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: