# ===== STAGE 1: Build Angular =====
FROM node:20 AS build-frontend
WORKDIR /app

COPY src/frontend/package*.json ./
RUN npm install
COPY src/frontend/ .
ARG CONFIGURATION=production
RUN npm run build -- --configuration=$CONFIGURATION

# ===== STAGE 2: Frontend Production (nginx) =====
FROM nginx:alpine AS build-frontend-prod
COPY --from=build-frontend /app/dist/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80