services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-backend-prod
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Information

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: build-frontend-prod
      args:
        CONFIGURATION: ${FRONTEND_CONFIG:-production}
    ports:
      - "4200:80"
