
-- ==============================================================================
-- PASSO 1.0 - LIMPEZA E CRIAÇÃO DO SCHEMA (IDEMPOTÊNCIA GARANTIDA)
-- ==============================================================================
DROP SCHEMA IF EXISTS LEGAL CASCADE;
CREATE SCHEMA LEGAL;

SET SEARCH_PATH TO LEGAL;

-- ==============================================================================
-- PASSO 2.0 - TABELAS DE REFERÊNCIA (LOOKUP TABLES)
-- ==============================================================================

-- ==============================================================================
-- PASSO 2.1 - TABELA: PROCESS_TYPE (TIPOS DE PROCESSOS)
-- ==============================================================================
CREATE TABLE LEGAL.PROCESS_TYPE (
    PROCESS_TYPE_ID SERIAL NOT NULL,
    PROCESS_TYPE_NAME VARCHAR(255) NOT NULL,
    PROCESS_TYPE_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- PRIMARY KEY
    CONSTRAINT PK_PROCESS_TYPE PRIMARY KEY (PROCESS_TYPE_ID),

    -- UNIQUE KEYS
    CONSTRAINT UK_PROCESS_TYPE_01 UNIQUE (PROCESS_TYPE_NAME)

	-- FOREIGN KEY
	-- N/A
);

-- ÍNDICES PARA AS FKS
-- N/A

-- ==============================================================================
-- PASSO 2.2 - TABELA: PROCESS_PHASE (FASES DO PROCESSO)
-- ==============================================================================
CREATE TABLE LEGAL.PROCESS_PHASE (
    PROCESS_PHASE_ID SERIAL NOT NULL,
    PROCESS_PHASE_NAME VARCHAR(255) NOT NULL,
    PROCESS_PHASE_DESCRIPTION TEXT,
    PROCESS_PHASE_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- PRIMARY KEY
    CONSTRAINT PK_PROCESS_PHASE PRIMARY KEY (PROCESS_PHASE_ID),

    -- UNIQUE KEYS
    CONSTRAINT UK_PROCESS_PHASE_01 UNIQUE (PROCESS_PHASE_NAME)

    -- FOREIGN KEYS
    -- N/A
);

-- ÍNDICES PARA AS FKS
-- N/A

-- ==============================================================================
-- PASSO 2.3 - TABELA: PROCESS_TYPE_PHASE (RELACIONA TIPOS DE PROCESSO COM FASES)
-- ==============================================================================
CREATE TABLE LEGAL.PROCESS_TYPE_PHASE (
    PROCESS_TYPE_PHASE_ID SERIAL NOT NULL,
    PROCESS_PHASE_ID INT NOT NULL,
    PROCESS_TYPE_ID INT NOT NULL,
    PROCESS_TYPE_PHASE_ORDER SMALLINT NOT NULL,
    PROCESS_TYPE_PHASE_IS_OPTIONAL BOOLEAN NOT NULL DEFAULT FALSE,
    PROCESS_TYPE_PHASE_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- PRIMARY KEY
    CONSTRAINT PK_PROCESS_TYPE_PHASE PRIMARY KEY (PROCESS_TYPE_PHASE_ID),

    -- FOREIGN KEYS
    CONSTRAINT FK_PROCESS_TYPE_PHASE_PROCESS_TYPE_01 FOREIGN KEY (PROCESS_TYPE_ID)
        REFERENCES PROCESS_TYPE(PROCESS_TYPE_ID),
    CONSTRAINT FK_PROCESS_TYPE_PHASE_PROCESS_PHASE_02 FOREIGN KEY (PROCESS_PHASE_ID)
        REFERENCES PROCESS_PHASE(PROCESS_PHASE_ID),

    -- UNIQUE KEYS
    CONSTRAINT UK_PROCESS_TYPE_PHASE_01 UNIQUE (PROCESS_TYPE_ID, PROCESS_PHASE_ID),
    CONSTRAINT UK_PROCESS_TYPE_PHASE_02 UNIQUE (PROCESS_TYPE_PHASE_ORDER, PROCESS_TYPE_ID)
);

-- ÍNDICES PARA AS FKS
CREATE INDEX IDX_PROCESS_TYPE_PHASE_01 ON PROCESS_TYPE_PHASE(PROCESS_TYPE_ID);
CREATE INDEX IDX_PROCESS_TYPE_PHASE_02 ON PROCESS_TYPE_PHASE(PROCESS_PHASE_ID);

-- ==============================================================================
-- PASSO 2.4 - TABELA: PROCESS_STATUS (STATUS DO PROCESSO)
-- ==============================================================================
CREATE TABLE LEGAL.PROCESS_STATUS (
    PROCESS_STATUS_ID SERIAL NOT NULL,
    PROCESS_STATUS_NAME VARCHAR(50) NOT NULL,
    PROCESS_STATUS_IS_FINAL BOOLEAN NOT NULL DEFAULT FALSE,
    PROCESS_STATUS_IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    PROCESS_STATUS_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- PRIMARY KEY
    CONSTRAINT PK_PROCESS_STATUS PRIMARY KEY (PROCESS_STATUS_ID),

    -- UNIQUE KEYS
    CONSTRAINT UK_PROCESS_STATUS_01 UNIQUE (PROCESS_STATUS_NAME)

    -- FOREIGN KEYS
    -- N/A
);

-- ÍNDICES PARA AS FKS
-- N/A


-- ==============================================================================
-- PASSO 2.5 - TABELA: PROCESS (PROCESSOS JURÍDICOS PRINCIPAIS)
-- ==============================================================================
CREATE TABLE LEGAL.PROCESS (
    PROCESS_ID UUID NOT NULL,
    PROCESS_NAME VARCHAR(255) NOT NULL,
    PROCESS_NUMBER VARCHAR(255) NOT NULL,
    CLIENT_ID UUID NOT NULL,
    LAWYER_ID UUID NOT NULL,
    PROCESS_ADVERSE_PART_NAME VARCHAR(255),
    PROCESS_OPPOSING_COUNSEL_NAME VARCHAR(255),
    PROCESS_CREATED_BY UUID NOT NULL,
    PROCESS_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESS_CLOSED_AT TIMESTAMP,
	PROCESS_DSC TEXT,
	PROCESS_NEXT_HEARING_DATE TIMESTAMP,
    PROCESS_PRIORITY SMALLINT NOT NULL,
    PROCESS_COURT_INFO TEXT NOT NULL,
    PROCESS_TYPE_PHASE_ID SMALLINT NOT NULL,
    PROCESS_STATUS_ID SMALLINT NOT NULL,


    -- PRIMARY KEY
    CONSTRAINT PK_PROCESS PRIMARY KEY (PROCESS_ID),

    -- FOREIGN KEYS
    CONSTRAINT FK_PROCESS_CLIENT_01 FOREIGN KEY (CLIENT_ID)
        REFERENCES CORE.CLIENT(CLIENT_ID),
    CONSTRAINT FK_PROCESS_LAWYER_02 FOREIGN KEY (LAWYER_ID)
        REFERENCES CORE.LAWYER(LAWYER_ID),
    CONSTRAINT FK_PROCESS_ADMIN_03 FOREIGN KEY (PROCESS_CREATED_BY)
        REFERENCES CORE.ADMIN(ADMIN_ID),
    CONSTRAINT FK_PROCESS_TYPE_PHASE_04 FOREIGN KEY (PROCESS_TYPE_PHASE_ID)
        REFERENCES LEGAL.PROCESS_TYPE_PHASE(PROCESS_TYPE_PHASE_ID),
    CONSTRAINT FK_PROCESS_STATUS_05 FOREIGN KEY (PROCESS_STATUS_ID)
        REFERENCES LEGAL.PROCESS_STATUS(PROCESS_STATUS_ID),

    -- UNIQUE KEYS
    CONSTRAINT UK_PROCESS_01 UNIQUE (PROCESS_NUMBER, CLIENT_ID, LAWYER_ID)
);

-- ÍNDICES PARA AS FKS
CREATE INDEX IDX_PROCESS_01 ON LEGAL.PROCESS(PROCESS_STATUS_PHASE_ID);
CREATE INDEX IDX_PROCESS_02 ON LEGAL.PROCESS(CLIENT_ID);
CREATE INDEX IDX_PROCESS_03 ON LEGAL.PROCESS(LAWYER_ID);
CREATE INDEX IDX_PROCESS_04 ON LEGAL.PROCESS(PROCESS_CREATED_BY);
CREATE INDEX IDX_PROCESS_05 ON LEGAL.PROCESS(PROCESS_TYPE_PHASE_ID);
CREATE INDEX IDX_PROCESS_06 ON LEGAL.PROCESS(PROCESS_STATUS_ID);

-- ==============================================================================
-- PASSO 2.6 - TABELA: PROCESS_LOG (REGISTRO DE AÇÕES NOS PROCESSOS)
-- ==============================================================================
CREATE TABLE LEGAL.PROCESS_LOG (
    PROCESS_LOG_ID UUID NOT NULL,
    PROCESS_ID UUID NOT NULL,
    UPDATED_BY UUID NOT NULL,
    ACTION_LOG_TYPE_ID SMALLINT NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OLD_VALUE JSONB NOT NULL,
    NEW_VALUE JSONB NOT NULL,

    -- PRIMARY KEY
    CONSTRAINT PK_PROCESS_LOG PRIMARY KEY (PROCESS_LOG_ID),

    -- FOREIGN KEYS
    CONSTRAINT FK_PROCESS_LOG_PROCESS_01 FOREIGN KEY (PROCESS_ID)
        REFERENCES LEGAL.PROCESS(PROCESS_ID),
    CONSTRAINT FK_PROCESS_LOG_ADMIN_02 FOREIGN KEY (UPDATED_BY)
        REFERENCES CORE.ADMIN(ADMIN_ID),
    CONSTRAINT FK_PROCESS_LOG_ACTION_TYPE_03 FOREIGN KEY (ACTION_LOG_TYPE_ID)
        REFERENCES CORE.ACTION_LOG_TYPE(ACTION_LOG_TYPE_ID)

    -- UNIQUE KEYS
    -- N/A
);

-- ÍNDICES PARA AS FKS
CREATE INDEX IDX_PROCESS_LOG_01 ON LEGAL.PROCESS_LOG(PROCESS_ID);
CREATE INDEX IDX_PROCESS_LOG_02 ON LEGAL.PROCESS_LOG(UPDATED_BY);
CREATE INDEX IDX_PROCESS_LOG_03 ON LEGAL.PROCESS_LOG(ACTION_LOG_TYPE_ID);

-- ==============================================================================
-- PASSO 2.7 - TABELA: DOCUMENT (ARQUIVOS ASSOCIADOS AO PROCESSO)
-- ==============================================================================
CREATE TABLE LEGAL.DOCUMENT (
    DOCUMENT_ID UUID NOT NULL,
    PROCESS_ID UUID NOT NULL,
    FILE_NAME VARCHAR(100) NOT NULL,
    FILE BYTEA NOT NULL,
    FILE_MIMETYPE VARCHAR(50) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY UUID NOT NULL,

    -- PRIMARY KEY
    CONSTRAINT PK_DOCUMENT PRIMARY KEY (DOCUMENT_ID),

    -- FOREIGN KEYS
    CONSTRAINT FK_DOCUMENT_PROCESS_01 FOREIGN KEY (PROCESS_ID)
        REFERENCES LEGAL.PROCESS(PROCESS_ID),
    CONSTRAINT FK_DOCUMENT_ADMIN_02 FOREIGN KEY (CREATED_BY)
        REFERENCES CORE.ADMIN(ADMIN_ID)

    -- UNIQUE KEYS
    -- N/A
);

-- ÍNDICES PARA AS FKS
CREATE INDEX IDX_DOCUMENT_01 ON LEGAL.DOCUMENT(PROCESS_ID);
CREATE INDEX IDX_DOCUMENT_02 ON LEGAL.DOCUMENT(CREATED_BY);


-- ==============================================================================
-- PASSO 2.8 - TABELA: DOCUMENT_LOG (REGISTRO DE AÇÕES EM DOCUMENTOS)
-- ==============================================================================
CREATE TABLE LEGAL.DOCUMENT_LOG (
    DOCUMENT_LOG_ID UUID NOT NULL,
    DOCUMENT_ID UUID NOT NULL,
    UPDATED_BY UUID NOT NULL,
    ACTION_LOG_TYPE_ID SMALLINT NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OLD_VALUE JSONB NOT NULL,
    NEW_VALUE JSONB NOT NULL,

    -- PRIMARY KEY
    CONSTRAINT PK_DOCUMENT_LOG PRIMARY KEY (DOCUMENT_LOG_ID),

    -- FOREIGN KEYS
    CONSTRAINT FK_DOCUMENT_LOG_DOCUMENT_01 FOREIGN KEY (DOCUMENT_ID)
        REFERENCES LEGAL.DOCUMENT(DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENT_LOG_ADMIN_02 FOREIGN KEY (UPDATED_BY)
        REFERENCES CORE.ADMIN(ADMIN_ID),
    CONSTRAINT FK_DOCUMENT_LOG_ACTION_TYPE_03 FOREIGN KEY (ACTION_LOG_TYPE_ID)
        REFERENCES CORE.ACTION_LOG_TYPE(ACTION_LOG_TYPE_ID)

    -- UNIQUE KEYS
    -- N/A
);

-- ÍNDICES PARA AS FKs
CREATE INDEX IDX_DOCUMENT_LOG_01 ON LEGAL.DOCUMENT_LOG(DOCUMENT_ID);
CREATE INDEX IDX_DOCUMENT_LOG_02 ON LEGAL.DOCUMENT_LOG(UPDATED_BY);
CREATE INDEX IDX_DOCUMENT_LOG_03 ON LEGAL.DOCUMENT_LOG(ACTION_LOG_TYPE_ID);