# .github/workflows/deploy-backend.yml
name: Deploy Backend to Render

on:
  push:
    branches:
      - main        # Para Production
      - development # Para Staging

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.API_KEY }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instala a CLI do Render
      - name: Install Render CLI
        run: curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh
      
      # Deploy de Produção (main)
      - name: Deploy to Production (main)
        if: github.ref == 'refs/heads/main'
        run: render deploy create ${{ secrets.RENDER_DEPLOY_ID_PROD }}

      # Deploy de Staging (development)
      - name: Deploy to Staging (development)
        if: github.ref == 'refs/heads/development'
        run: render deploy create ${{ secrets.RENDER_DEPLOY_ID_DEVLOPMENT }}